config/routes.rb
HespTodo::Application.routes.draw do

  resources :tasks

  root to: 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :title, :description, :status, :day, :end_time, :start_time

  def time_range
    "#{start_time.strftime('%H:%M')} - #{end_time.strftime('%H:%M')}" if start_time && end_time
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @new_task = Task.new
  end

  def create
    @task = Task.new(params[:task])

    if @task.save
      respond_to do |format|
        format.json { render json: @task.to_json }
        format.html { redirect_to tasks_path  }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HespTodo
    %link(rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Averia+Gruesa+Libre|Miss+Fajardose|Marcellus+SC|Handlee|Sarina|Walter+Turncoat|Gloria+Hallelujah' rel='stylesheet' type='text/css')
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .header
      .span8#todo_title Hesp ToDo

    .container
      .row-fluid
        .span4.day-title
          %h4=l Date.today, format: :long
          =hidden_field :selected, :date, value: Date.today.strftime("%d/%m/%Y")
        .span4.offset4.context-title
          %h4 Pessoal
      %br
      .row-fluid
        .span12.content
          = yield

    .footer

app/views/tasks/_form.html.haml
= form_for @task, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.text_field :status, :class => 'text_field'
  .control-group
    = f.label :start_time, :class => 'control-label'
    .controls
      = f.time_select :start_time, :class => 'time_select'
  .control-group
    = f.label :end_time, :class => 'control-label'
    .controls
      = f.time_select :end_time, :class => 'time_select'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn'

app/views/tasks/_modal_form.html.haml
=form_for task, remote: true do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.text_field :status, :class => 'text_field'
  .control-group
    = f.label :start_time, :class => 'control-label'
    .controls
      = f.time_select :start_time, :class => 'time_select'
  .control-group
    = f.label :end_time, :class => 'control-label'
    .controls
      = f.time_select :end_time, :class => 'time_select'
 

app/views/tasks/_modal_form_fields.html.haml
.form-horizontal
  .control-group
    = f.label :day, :class => 'control-label'
    .controls
      = f.text_field :day, :class => 'datepicker'
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'

  .control-group
    = f.label :time, "Início / Fim", :class => 'control-label'
    .controls
      .form-inline
        .input-append.bootstrap-timepicker
          = f.text_field :start_time, :class => 'timepicker input-mini'
          %span.add-on 
            %i.icon-time
        .input-append.bootstrap-timepicker
          = f.text_field :end_time, :class => 'timepicker input-mini'
          %span.add-on 
            %i.icon-time

app/views/tasks/_task.html.haml
%li.task-li
  .label.task-time
    = task.time_range
  .task-title
    = task.title

app/views/tasks/edit.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/tasks/index.html.haml
#new-task-modal.modal.hide.fade.in(style="display: none;")  
  .modal-header
    %a(class="close" data-dismiss="modal") ×
    %h3 Nova Tarefa
  = form_for @new_task, html: { remote: true } do |f|
    .modal-body{style:'height: 300px'}
      = render partial:'modal_form_fields', locals:{f:f}
    .modal-footer
      = f.submit 'Criar', class:'btn btn-success'
      = link_to 'Cancelar', tasks_path, class:'btn', data: {dismiss:'modal'}

#task-list
  %ul.task-list.sortable
    = render @tasks

  .add-task
    =link_to raw("<i class='icon-plus'></i>"), "#new-task-modal", data: {toggle: 'modal'}, id: 'new-task-modal-button'

app/views/tasks/new.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/tasks/show.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @task.title
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @task.description
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @task.status
%p
  %strong= model_class.human_attribute_name(:start_time) + ':'
  %br
  = @task.start_time
%p
  %strong= model_class.human_attribute_name(:end_time) + ':'
  %br
  = @task.end_time

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), tasks_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(@task), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(@task), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'